/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/blender/bergenia_bow.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function BergeniaBow(props) {
  const { nodes, materials } = useGLTF('/blender/bergenia_bow.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[18.122, 19.361, -0.478]} scale={-0.5}>
        <mesh geometry={nodes.Cube185.geometry} material={materials['medium wood']} />
        <mesh geometry={nodes.Cube185_1.geometry} material={materials['dark wood']} />
        <mesh geometry={nodes.Cube185_2.geometry} material={materials['light wood']} />
        <mesh geometry={nodes.Cube185_3.geometry} material={materials['dark pink']} />
        <mesh geometry={nodes.Cube185_4.geometry} material={materials['grey pink']} />
        <mesh geometry={nodes.Cube185_5.geometry} material={materials['light pink']} />
        <mesh geometry={nodes.Cube185_6.geometry} material={materials['white pink']} />
        <mesh geometry={nodes.Cube185_7.geometry} material={materials['medium pink']} />
        <mesh geometry={nodes.Cube185_8.geometry} material={materials['dark green']} />
        <mesh geometry={nodes.Cube185_9.geometry} material={materials['medium wood.017']} />
        <mesh geometry={nodes.Cube185_10.geometry} material={materials['medium wood.001']} />
        <mesh geometry={nodes.Cube185_11.geometry} material={materials['medium wood.002']} />
        <mesh geometry={nodes.Cube185_12.geometry} material={materials['medium wood.005']} />
        <mesh geometry={nodes.Cube185_13.geometry} material={materials['dark wood.006']} />
        <mesh geometry={nodes.Cube185_14.geometry} material={materials['dark wood.007']} />
        <mesh geometry={nodes.Cube185_15.geometry} material={materials['dark wood.008']} />
        <mesh geometry={nodes.Cube185_16.geometry} material={materials['medium wood.011']} />
        <mesh geometry={nodes.Cube185_17.geometry} material={materials['light wood.011']} />
        <mesh geometry={nodes.Cube185_18.geometry} material={materials['dark pink.011']} />
        <mesh geometry={nodes.Cube185_19.geometry} material={materials['light wood.012']} />
        <mesh geometry={nodes.Cube185_20.geometry} material={materials['dark pink.012']} />
        <mesh geometry={nodes.Cube185_21.geometry} material={materials['medium wood.012']} />
        <mesh geometry={nodes.Cube185_22.geometry} material={materials['medium wood.015']} />
        <mesh geometry={nodes.Cube185_23.geometry} material={materials['medium wood.016']} />
        <mesh geometry={nodes.Cube185_24.geometry} material={materials['light wood.017']} />
        <mesh geometry={nodes.Cube185_25.geometry} material={materials['dark wood.017']} />
        <mesh geometry={nodes.Cube185_26.geometry} material={materials['medium wood.018']} />
        <mesh geometry={nodes.Cube185_27.geometry} material={materials['dark wood.018']} />
        <mesh geometry={nodes.Cube185_28.geometry} material={materials['light wood.018']} />
        <mesh geometry={nodes.Cube185_29.geometry} material={materials['medium wood.021']} />
        <mesh geometry={nodes.Cube185_30.geometry} material={materials['light wood.021']} />
        <mesh geometry={nodes.Cube185_31.geometry} material={materials['medium wood.022']} />
        <mesh geometry={nodes.Cube185_32.geometry} material={materials['light wood.022']} />
        <mesh geometry={nodes.Cube185_33.geometry} material={materials['dark pink.025']} />
        <mesh geometry={nodes.Cube185_34.geometry} material={materials['dark pink.026']} />
        <mesh geometry={nodes.Cube185_35.geometry} material={materials['medium wood.027']} />
        <mesh geometry={nodes.Cube185_36.geometry} material={materials['medium wood.029']} />
        <mesh geometry={nodes.Cube185_37.geometry} material={materials['white pink.030']} />
        <mesh geometry={nodes.Cube185_38.geometry} material={materials['white pink.031']} />
        <mesh geometry={nodes.Cube185_39.geometry} material={materials['medium wood.032']} />
        <mesh geometry={nodes.Cube185_40.geometry} material={materials['light wood.032']} />
        <mesh geometry={nodes.Cube185_41.geometry} material={materials['dark wood.033']} />
        <mesh geometry={nodes.Cube185_42.geometry} material={materials['light wood.033']} />
        <mesh geometry={nodes.Cube185_43.geometry} material={materials['medium wood.033']} />
        <mesh geometry={nodes.Cube185_44.geometry} material={materials['medium wood.034']} />
        <mesh geometry={nodes.Cube185_45.geometry} material={materials['dark wood.034']} />
        <mesh geometry={nodes.Cube185_46.geometry} material={materials['light wood.034']} />
        <mesh geometry={nodes.Cube185_47.geometry} material={materials['medium wood.035']} />
        <mesh geometry={nodes.Cube185_48.geometry} material={materials['medium wood.036']} />
        <mesh geometry={nodes.Cube185_49.geometry} material={materials['medium wood.038']} />
        <mesh geometry={nodes.Cube185_50.geometry} material={materials['light wood.038']} />
        <mesh geometry={nodes.Cube185_51.geometry} material={materials['dark pink.039']} />
        <mesh geometry={nodes.Cube185_52.geometry} material={materials['dark pink.040']} />
        <mesh geometry={nodes.Cube185_53.geometry} material={materials['dark wood.041']} />
        <mesh geometry={nodes.Cube185_54.geometry} material={materials['medium wood.044']} />
        <mesh geometry={nodes.Cube185_55.geometry} material={materials['light wood.044']} />
        <mesh geometry={nodes.Cube185_56.geometry} material={materials['dark pink.044']} />
        <mesh geometry={nodes.Cube185_57.geometry} material={materials['light wood.045']} />
        <mesh geometry={nodes.Cube185_58.geometry} material={materials['medium wood.045']} />
        <mesh geometry={nodes.Cube185_59.geometry} material={materials['dark wood.047']} />
        <mesh geometry={nodes.Cube185_60.geometry} material={materials['dark wood.048']} />
        <mesh geometry={nodes.Cube185_61.geometry} material={materials['dark wood.049']} />
        <mesh geometry={nodes.Cube185_62.geometry} material={materials['medium wood.049']} />
        <mesh geometry={nodes.Cube185_63.geometry} material={materials['light wood.050']} />
        <mesh geometry={nodes.Cube185_64.geometry} material={materials['dark pink.050']} />
        <mesh geometry={nodes.Cube185_65.geometry} material={materials['grey pink.050']} />
        <mesh geometry={nodes.Cube185_66.geometry} material={materials['light pink.051']} />
        <mesh geometry={nodes.Cube185_67.geometry} material={materials['white pink.050']} />
        <mesh geometry={nodes.Cube185_68.geometry} material={materials['medium pink.051']} />
        <mesh geometry={nodes.Cube185_69.geometry} material={materials['medium wood.050']} />
        <mesh geometry={nodes.Cube185_70.geometry} material={materials['medium wood.051']} />
        <mesh geometry={nodes.Cube185_71.geometry} material={materials['medium wood.052']} />
        <mesh geometry={nodes.Cube185_72.geometry} material={materials['medium wood.054']} />
        <mesh geometry={nodes.Cube185_73.geometry} material={materials['medium wood.055']} />
        <mesh geometry={nodes.Cube185_74.geometry} material={materials['medium wood.058']} />
        <mesh geometry={nodes.Cube185_75.geometry} material={materials['medium wood.059']} />
        <mesh geometry={nodes.Cube185_76.geometry} material={materials['medium wood.066']} />
        <mesh geometry={nodes.Cube185_77.geometry} material={materials['medium wood.067']} />
        <mesh geometry={nodes.Cube185_78.geometry} material={materials['medium wood.068']} />
        <mesh geometry={nodes.Cube185_79.geometry} material={materials['medium wood.069']} />
        <mesh geometry={nodes.Cube185_80.geometry} material={materials['medium wood.071']} />
        <mesh geometry={nodes.Cube185_81.geometry} material={materials['medium green']} />
        <mesh geometry={nodes.Cube185_82.geometry} material={materials.green} />
        <mesh geometry={nodes.Cube185_83.geometry} material={materials['dark green.001']} />
        <mesh geometry={nodes.Cube185_84.geometry} material={materials['light pink.085']} />
        <mesh geometry={nodes.Cube029.geometry} material={materials['white pink']} position={[23.245, 11.721, 0.043]} />
        <mesh geometry={nodes.Cube030.geometry} material={materials['dark pink']} position={[-2.755, 29.721, 0.043]} />
        <group position={[17.245, 19.721, -1.957]}>
          <mesh geometry={nodes.Cube032.geometry} material={materials['grey pink']} />
          <mesh geometry={nodes.Cube032_1.geometry} material={materials['dark pink']} />
        </group>
        <mesh geometry={nodes.Cube034.geometry} material={materials['white pink']} position={[11.245, 27.721, -1.957]} />
        <mesh geometry={nodes.Cube035.geometry} material={materials['grey pink']} position={[9.245, 25.721, 0.043]} />
        <group position={[3.245, 19.721, 4.043]}>
          <mesh geometry={nodes.Cube039.geometry} material={materials['dark pink']} />
          <mesh geometry={nodes.Cube039_1.geometry} material={materials['light pink']} />
          <mesh geometry={nodes.Cube039_2.geometry} material={materials['medium pink']} />
        </group>
        <group position={[15.245, 3.721, -3.957]}>
          <mesh geometry={nodes.Cube041.geometry} material={materials['light pink']} />
          <mesh geometry={nodes.Cube041_1.geometry} material={materials['medium pink']} />
          <mesh geometry={nodes.Cube041_2.geometry} material={materials['light pink.027']} />
          <mesh geometry={nodes.Cube041_3.geometry} material={materials['medium pink.027']} />
        </group>
        <mesh geometry={nodes.Cube107.geometry} material={materials['medium pink']} position={[3.245, 33.721, 4.043]} />
        <mesh geometry={nodes.Cube108.geometry} material={materials['grey pink']} position={[21.245, 29.721, -3.957]} />
        <mesh geometry={nodes.Cube109.geometry} material={materials['light pink']} position={[11.245, 9.721, 4.043]} />
        <group position={[30.033, -20.06, 3.043]} rotation={[0, 0, Math.PI]} scale={0.5}>
          <mesh geometry={nodes.Cube779.geometry} material={materials['light pink.080']} />
          <mesh geometry={nodes.Cube779_1.geometry} material={materials['green.009']} />
          <mesh geometry={nodes.Cube779_2.geometry} material={materials['medium green.010']} />
          <mesh geometry={nodes.Cube779_3.geometry} material={materials['medium green.011']} />
          <mesh geometry={nodes.Cube779_4.geometry} material={materials['dark green.004']} />
          <mesh geometry={nodes.Cube779_5.geometry} material={materials['grey pink.077']} />
          <mesh geometry={nodes.Cube779_6.geometry} material={materials['medium pink.079']} />
          <mesh geometry={nodes.Cube779_7.geometry} material={materials['green.010']} />
          <mesh geometry={nodes.Cube779_8.geometry} material={materials['medium green.012']} />
          <mesh geometry={nodes.Cube779_9.geometry} material={materials['medium green.013']} />
          <mesh geometry={nodes.Cube779_10.geometry} material={materials['green.011']} />
          <mesh geometry={nodes.Cube779_11.geometry} material={materials['light pink.082']} />
          <mesh geometry={nodes.Cube779_12.geometry} material={materials['medium pink.081']} />
          <mesh geometry={nodes.Cube779_13.geometry} material={materials['yellow.002']} />
          <mesh geometry={nodes.Cube779_14.geometry} material={materials['dark yellow.002']} />
        </group>
        <group position={[30.878, -20.305, -2.957]} scale={0.5}>
          <mesh geometry={nodes.Cube774.geometry} material={materials['light pink.076']} />
          <mesh geometry={nodes.Cube774_1.geometry} material={materials['green.006']} />
          <mesh geometry={nodes.Cube774_2.geometry} material={materials['medium green.006']} />
          <mesh geometry={nodes.Cube774_3.geometry} material={materials['medium green.007']} />
          <mesh geometry={nodes.Cube774_4.geometry} material={materials['dark green.003']} />
          <mesh geometry={nodes.Cube774_5.geometry} material={materials['grey pink.074']} />
          <mesh geometry={nodes.Cube774_6.geometry} material={materials['medium pink.076']} />
          <mesh geometry={nodes.Cube774_7.geometry} material={materials['green.007']} />
          <mesh geometry={nodes.Cube774_8.geometry} material={materials['medium green.008']} />
          <mesh geometry={nodes.Cube774_9.geometry} material={materials['medium green.009']} />
          <mesh geometry={nodes.Cube774_10.geometry} material={materials['green.008']} />
          <mesh geometry={nodes.Cube774_11.geometry} material={materials['light pink.078']} />
          <mesh geometry={nodes.Cube774_12.geometry} material={materials['medium pink.078']} />
          <mesh geometry={nodes.Cube774_13.geometry} material={materials['yellow.001']} />
          <mesh geometry={nodes.Cube774_14.geometry} material={materials['dark yellow.001']} />
        </group>
      </group>
      <mesh geometry={nodes.Cube110.geometry} material={materials['dark yellow']} position={[-14.5, 0.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube113.geometry} material={materials.yellow} position={[-14.5, 1.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube119.geometry} material={materials['light pink']} position={[-15.5, 0.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube120.geometry} material={materials['light pink']} position={[-15.5, 1.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube121.geometry} material={materials['light pink']} position={[-13.5, 1.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube123.geometry} material={materials['light pink']} position={[-13.5, -0.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube124.geometry} material={materials['grey pink']} position={[-15.5, -0.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube134.geometry} material={materials['light pink']} position={[-14.5, -0.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube391.geometry} material={materials['medium pink']} position={[-11.5, 1.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube392.geometry} material={materials['medium pink']} position={[-12.5, 0.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube393.geometry} material={materials['light pink']} position={[-12.5, 1.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube394.geometry} material={materials['light pink']} position={[-14.5, 2.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube395.geometry} material={materials['light pink']} position={[-11.5, -0.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube397.geometry} material={materials['medium pink']} position={[-17.5, 1.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube398.geometry} material={materials['medium pink']} position={[-16.5, -2.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube399.geometry} material={materials['light pink']} position={[-17.5, -0.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube400.geometry} material={materials['grey pink']} position={[-13.5, 0.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube401.geometry} material={materials['light pink']} position={[-16.5, 3.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube402.geometry} material={materials['light pink']} position={[-17.5, 2.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube403.geometry} material={materials['light pink']} position={[-13.5, 3.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube404.geometry} material={materials['light pink']} position={[-13.5, 2.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube405.geometry} material={materials['medium pink']} position={[-16.5, 0.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube407.geometry} material={materials['medium pink']} position={[-12.5, -1.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube408.geometry} material={materials['light pink']} position={[-12.5, -0.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube411.geometry} material={materials['light pink']} position={[-16.5, 2.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube412.geometry} material={materials['grey pink']} position={[-15.5, 2.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube414.geometry} material={materials['light pink']} position={[-16.5, 1.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube415.geometry} material={materials['light pink']} position={[-16.5, -1.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube112.geometry} material={materials['light pink']} position={[-13.5, -1.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube114.geometry} material={materials['light pink']} position={[-16.5, -0.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube390.geometry} material={materials['light pink.073']} position={[-12.5, 2.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube406.geometry} material={materials['light pink']} position={[-17.5, -1.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube125.geometry} material={materials['medium pink.075']} position={[-15.5, -1.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube409.geometry} material={materials['medium green.002']} position={[-14.5, -1.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube410.geometry} material={materials['medium green.003']} position={[-13.5, -2.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube396.geometry} material={materials['green.001']} position={[-14.5, -2.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube413.geometry} material={materials['green.002']} position={[-13.5, -3.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube416.geometry} material={materials['dark green.002']} position={[-17.5, 0.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube417.geometry} material={materials['medium green.004']} position={[-18.5, 1.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube418.geometry} material={materials['medium green.005']} position={[-18.5, 0.5, 2.5]} scale={-0.5} />
      <mesh geometry={nodes.Cube419.geometry} material={materials['green.005']} position={[-19.5, 1.5, 2.5]} scale={-0.5} />
    </group>
  )
}

useGLTF.preload('/blender/bergenia_bow.gltf')
